# Site settings
title: Home
description: >-
 This site has been used to share my CTF solutions <a href="https://github.com/shemkumar" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Asia/Jakarta
image: assets/img/ogp.png
repo: https://github.com/piharpi/jekyll-klise
mode: dark

# Profile settings
author:
  name: Shemkumar
  bio: >-
    I am a dedicated CTF player with a strong passion for cybersecurity and problem-solving. Over the years, I have participated in numerous CTF competitions, sharpening my skills in various domains such as cryptography, reverse engineering, web exploitation, forensics, and more. My journey in cybersecurity is driven by a constant desire to learn and adapt to the ever-changing landscape of digital threats. <a href="https://github.com/shemkumar" target="_blank" rel="noopener">@github</a>.
  username: shemkumar
  github: shemkumar
  email: thunderbolt20200@gmail.com
  avatar: /assets/img/avatar.jpg

# URL settings
url: "https://shemkumar.github.io"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
